import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
    return (
        <main className='flex h-screen items-center bg-gradient-to-tr from-black to-sky-800'>
            <Head>
                <title>Next.js Orchid ORM</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className='flex w-screen-2xl rounded-lg shadow-md h-auto p-8 mx-auto bg-gray-200'>
                <section>
                    <h1 className='text-2xl font-semibold'> It Works! </h1>
                    <p className='mt-4'>
                        This is the default page when we working on it. Here are some reasons why
                        you are viewing this page:
                    </p>
                    <ul className='my-4 list-disc list-inside'>
                        <li>This is the default web page for the site.</li>
                        <li>
                            This page used to <span className='underline'>test the server</span>{' '}
                            configuration.
                        </li>
                        <li>Site owner haven&rsquo;t uploaded your website yet.</li>
                        <li>Site owner still working on something great for you.</li>
                    </ul>
                    <p>
                        Please contact the{' '}
                        <Link
                            href='https://github.com/riipandi'
                            className='text-indigo-700 hover:text-indigo-500'
                            rel='noopener noreferrer'
                            target='_blank'
                        >
                            site owner
                        </Link>{' '}
                        to get more information.
                    </p>
                </section>
            </div>
        </main>
    )
}
