import Head from 'next/head'
import Link from 'next/link'
import { signOut, useSession } from 'next-auth/react'

export default function Home() {
  const { data: sessionData } = useSession()

  return (
    <main className='flex h-screen items-center bg-gradient-to-tr from-black to-sky-800'>
      <Head>
        <title>Next.js Orchid ORM</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-screen-2xl mx-auto flex h-auto rounded-lg bg-gray-200 p-8 shadow-md'>
        <section>
          <h1 className='text-2xl font-semibold'> It Works! </h1>
          <p className='mt-4'>
            This is the default page when we working on it. Here are the reasons why:
          </p>
          <ul className='my-4 list-inside list-disc'>
            <li>This is the default web page for the site.</li>
            <li>
              This page used to <span className='underline'>test the server</span> configuration.
            </li>
            <li>Site owner haven&rsquo;t uploaded your website yet.</li>
            <li>Site owner still working on something great for you.</li>
          </ul>
          <p>
            Please contact the{' '}
            <Link
              href='https://github.com/riipandi'
              className='text-indigo-700 hover:text-indigo-500'
              rel='noopener noreferrer'
              target='_blank'
            >
              site owner
            </Link>{' '}
            to get more information.
          </p>
          {sessionData ? (
            <p className='mt-4'>
              {`Logged in as ${sessionData.user?.name} (${sessionData.user?.email}) `}
              <button
                type='button'
                className='text-indigo-700 hover:text-indigo-500'
                onClick={() => signOut()}
              >
                sign out &rarr;
              </button>
            </p>
          ) : (
            <p className='mt-4'>
              You can try{' '}
              <Link href='/api/auth/signin' className='text-indigo-700 hover:text-indigo-500'>
                sign in
              </Link>{' '}
              into account area.
            </p>
          )}
        </section>
      </div>
    </main>
  )
}
