import Head from 'next/head'

export default function LoginPage() {
  // const response = await signIn('login', {
  //   email: '',
  //   password: '',
  //   redirect: false,
  // })

  return (
    <main className='flex h-screen items-center bg-gradient-to-tr from-black to-sky-800'>
      <Head>
        <title>Login</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-screen-2xl mx-auto flex h-auto rounded-lg bg-gray-200 p-8 shadow-md'>
        <section>
          <h1 className='text-2xl font-semibold'>Login</h1>
          <div className='mt-4'>Do something!</div>
        </section>
      </div>
    </main>
  )
}
